biografias = [
    {
        "nombre": "Stiven Brandon Rincon",
        "fechaNacimiento": "10 de enero de 2000",
        "descripcion": "Desarrollador backend con experiencia\nen Python y Java.",
        "imagen1": r"C:\Users\pc\Documents\pr-ctica-2-g1-e1\src\Imagenes\foto_brandon1.png",
        "imagen2": r"C:\Users\pc\Documents\pr-ctica-2-g1-e1\src\Imagenes\foto_brandon2.png",
        "imagen3": r"C:\Users\pc\Documents\pr-ctica-2-g1-e1\src\Imagenes\foto_brandon3.png",
        "imagen4": r"C:\Users\pc\Documents\pr-ctica-2-g1-e1\src\Imagenes\huy-phan-UaBR3TyluF4-unsplash.png",
    },
    {
        "nombre": "Juan Camilo Moreano Urresty",
        "fechaNacimiento": "5 de junio de 2002",
        "descripcion": "estudiate de la universidad nacional\ncon experiencia en python y java",
        "imagen1": r"C:\Users\pc\Documents\pr-ctica-2-g1-e1\src\Imagenes\foto_camilo1.png",
        "imagen2": r"C:\Users\pc\Documents\pr-ctica-2-g1-e1\src\Imagenes\foto_camilo2.png",
        "imagen3": r"C:\Users\pc\Documents\pr-ctica-2-g1-e1\src\Imagenes\foto_camilo3.png",
        "imagen4": r"C:\Users\pc\Documents\pr-ctica-2-g1-e1\src\Imagenes\foto_camilo4.png",
    },
    #{
    #   "nombre": "Luis Mario Cardona Ramirez ",
    #    "fechaNacimiento": "10 de enero de 2000",
    #    "descripcion": "Desarrollador backend con experiencia\nen Python y Java.",
    #    "imagen1": r"direccion de la foto",
    #    "imagen2": r"direccion de la foto",
    #    "imagen3": r"direccion de la foto",
    #    "imagen4": r"direccion de la foto",
    #},
    # {
    #     "nombre": "David Fernando Ceron Quintero",
    #     "fechaNacimiento": "10 de enero de 2000",
    #     "descripcion": "Desarrollador backend con experiencia\nen Python y Java.",
    #     "imagen1": r"direccion de la foto",
    #    "imagen2": r"direccion de la foto",
    #    "imagen3": r"direccion de la foto",
    #    "imagen4": r"direccion de la foto",
    # },
    # {
    #     "nombre": "Santiago Abelardo Salcedo Rodriguez",
    #     "fechaNacimiento": "10 de enero de 2000",
    #     "descripcion": "Desarrollador backend con experiencia\nen Python y Java.",
    #     "imagen1": r"direccion de la foto",
    #    "imagen2": r"direccion de la foto",
    #    "imagen3": r"direccion de la foto",
    #    "imagen4": r"direccion de la foto",
    # },
]
